spring:
  main:
    banner-mode: off
  application:
    name: faq-service
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  security:
    jwt:
      secret-key: ${SECURITY_JWT_SECRET_KEY}
      access-expiration: ${SECURITY_JWT_ACCESS_EXPIRATION:600}
      refresh-expiration: ${SECURITY_JWT_REFRESH_EXPIRATION:86400}
  cache:
    type: redis
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
      password: ${SPRING_DATA_REDIS_PASSWORD}
      enabled: ${SPRING_DATA_REDIS_ENABLED:true}
      flush-on-startup: ${SPRING_DATA_REDIS_FLUSH_ON_STARTUP:true}

server:
  port: 8080

scheduler:
  defaultLockAtMostFor: ${SCHEDULER_DEFAULT_LOCK_AT_MOST_FOR:30m}
  faq-sync:
    cron: ${SCHEDULER_FAQ_SYNC_CRON:0 */15 * * * *}
    enabled: ${SCHEDULER_FAQ_SYNC_ENABLED:true}
    lockAtLeastFor: ${SCHEDULER_FAQ_SYNC_LOCK_AT_LEAST_FOR:1m}
    lockAtMostFor: ${SCHEDULER_FAQ_SYNC_LOCK_AT_MOST_FOR:20m}