CREATE TABLE faq
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    question   VARCHAR(256),
    answer     TEXT                                    NOT NULL,
    keywords   JSONB,
    created_by BIGINT                                  NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    in_mongo   BOOLEAN                                 NOT NULL DEFAULT FALSE,
    active     BOOLEAN                                 NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_faq PRIMARY KEY (id)
);


ALTER TABLE faq
    ADD CONSTRAINT FK_FAQ_ON_CREATED_BY FOREIGN KEY (created_by) REFERENCES users (id);